# docker-compose.yml

version: '3.8'

services:
  app:
    build: .
    container_name: ghost_kitchen_ai
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - APP_PORT=8000
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - ghost_kitchen_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ghost_kitchen_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ghost_kitchen_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: ghost_kitchen_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - ghost_kitchen_network
    restart: unless-stopped

networks:
  ghost_kitchen_network:
    driver: bridge

volumes:
  redis_data: